### ISSUE TITLE
How is the progress of merging this to neovim?

### ISSUE THREAD

**Issue by neo451** [uga-rosa/utf8.nvim#2]
Really like to see this improved and merged into neovim main, because I am working on a feed reader and a Chinese handling engine in neovim, both depend on this library.
I wanted to raise the issue to neovim main and work on it myself to write one that more fits my needs and maybe get it into main, but then I saw your reddit post and your plan, just want to know why there has not been any movements toward that?

**Comment by uga-rosa** [comment]
Unfortunately, the integration into the Neovim core was rejected, and the PR to Plenary has been left unattended for two years, so I gave up and closed it.

https://github.com/neovim/neovim/pull/16439
https://github.com/nvim-lua/plenary.nvim/pull/273

**Comment by neo451** [comment]
I see. Thank you for your work!
